name = "yapster"
main = "build/index.js"
compatibility_date = "2023-10-30"

[build]
command = "npm run build"

[env.production]
name = "yapster"
workers_dev = true

[env.development]
name = "yapster-dev"
workers_dev = true 